# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# 👇 ESTO ES CLAVE para que app_links y Firebase funcionen correctamente
use_frameworks!
use_modular_headers!

flutter_application_path = '../..'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_ios_podfile_setup

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # 👇 Esto permite que todos los plugins (como app_links) se integren correctamente
  install_all_flutter_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
