// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_t2FZZakK5M_lVl40zj3EbHVI29ZFkA',
    appId: '1:254258185653:web:1ff869042a65325f1105fc',
    messagingSenderId: '254258185653',
    projectId: 'draftclub-a00ea',
    authDomain: 'draftclub-a00ea.firebaseapp.com',
    storageBucket: 'draftclub-a00ea.firebasestorage.app',
    measurementId: 'G-PCDQHCD584',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiihgaG-5kGn5IrA_xe483B3OfwHG0Ews',
    appId: '1:254258185653:android:5ae96d8587e4baa31105fc',
    messagingSenderId: '254258185653',
    projectId: 'draftclub-a00ea',
    storageBucket: 'draftclub-a00ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-alROrIwzaSWXRJ79XpoUJ29eiODIFDc',
    appId: '1:254258185653:ios:ae04333d09c1d0fd1105fc',
    messagingSenderId: '254258185653',
    projectId: 'draftclub-a00ea',
    storageBucket: 'draftclub-a00ea.firebasestorage.app',
    iosBundleId: 'com.example.draftclubMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-alROrIwzaSWXRJ79XpoUJ29eiODIFDc',
    appId: '1:254258185653:ios:ae04333d09c1d0fd1105fc',
    messagingSenderId: '254258185653',
    projectId: 'draftclub-a00ea',
    storageBucket: 'draftclub-a00ea.firebasestorage.app',
    iosBundleId: 'com.example.draftclubMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm_t2FZZakK5M_lVl40zj3EbHVI29ZFkA',
    appId: '1:254258185653:web:a08f19bebbc4e55c1105fc',
    messagingSenderId: '254258185653',
    projectId: 'draftclub-a00ea',
    authDomain: 'draftclub-a00ea.firebaseapp.com',
    storageBucket: 'draftclub-a00ea.firebasestorage.app',
    measurementId: 'G-XK0H616PVL',
  );

}