# This file was automatically generated by Flutter. 
# It provides iOS-specific CocoaPods helper methods for Flutter integration.

require 'fileutils'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __dir__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run 'flutter pub get' first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end

  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try 'flutter pub get'."
end

def flutter_export_environment_path
  File.expand_path(File.join('..', 'Flutter', 'flutter_export_environment.sh'), __dir__)
end

def flutter_podhelper_path
  File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))
end

require flutter_podhelper_path

def flutter_additional_ios_build_settings(target)
  # This makes sure Flutter's build settings are added properly.
  flutter_additional_ios_build_settings_base(target)
end
